name: Django testing and deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_on_server:
    runs-on: ubuntu-20.04
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: 'False'
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      ENGINE: ${{ secrets.DB_ENGINE }}
      USER: ${{ secrets.DB_USER }}
      PASSWORD: ${{ secrets.DB_PASSWORD }}
      NAME: ${{ secrets.DB_NAME }}
      HOST: ${{ secrets.DB_HOST }}
      PORT: ${{ secrets.DB_PORT }}

    services:
      postgres_db:
        image: postgres:13
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ env.USER }}
          POSTGRES_PASSWORD: ${{ env.PASSWORD }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Проверка репозитория на наличие изменений.
        uses: actions/checkout@v4

      - name: Установка Python.
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Установка зависимостей.
        run: pip install -r requirements.txt

      - name: Линтинг
        run: flake8 logistic/

      - name: Тестирование
        run: pytest
        env:
          SECRET_KEY: ${{ env.SECRET_KEY }}
          DEBUG: 'False'
          ALLOWED_HOSTS: ${{ env.ALLOWED_HOSTS }}
          ENGINE: ${{ env.ENGINE }}
          USER: ${{ env.USER }}
          PASSWORD: ${{ env.PASSWORD }}
          NAME: ${{ env.NAME }}
          HOST: ${{ env.HOST }}
          PORT: ${{ env.PORT }}

